### ISSUE TITLE
Gmail Login failed

### ISSUE THREAD

**Issue by abuaccount** [pythontester192/LIKE4LIKE-BOT-USING-PYTHON#7]
Hey,
Up to now I like the bots. But I am getting a error message when I'm trying the AddMeFast Credit Bot.
C:\Users\User\Desktop\FollowerBot-main>python get_credit_on_AddMeFast.py
Logged in AddmeFast. Your current point is: 0
Logged in Facebook.
Something went wrong in Gmail login process.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\FollowerBot-main\get_credit_on_AddMeFast.py", line 945, in <module>
    amf.login_instagram()
  File "C:\Users\User\Desktop\FollowerBot-main\get_credit_on_AddMeFast.py", line 116, in login_instagram
    cookies = WebDriverWait(self.browser, 10).until(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x0049F243]
        (No symbol) [0x00427FD1]
        (No symbol) [0x0031D04D]
        (No symbol) [0x0034C0B0]
        (No symbol) [0x0034C22B]
        (No symbol) [0x0037E612]
        (No symbol) [0x003685D4]
        (No symbol) [0x0037C9EB]
        (No symbol) [0x00368386]
        (No symbol) [0x0034163C]
        (No symbol) [0x0034269D]
        GetHandleVerifier [0x00739A22+2655074]
        GetHandleVerifier [0x0072CA24+2601828]
        GetHandleVerifier [0x00548C0A+619850]
        GetHandleVerifier [0x00547830+614768]
        (No symbol) [0x004305FC]
        (No symbol) [0x00435968]
        (No symbol) [0x00435A55]
        (No symbol) [0x0044051B]
        BaseThreadInitThunk [0x7704FA29+25]
        RtlGetAppContainerNamedObjectPath [0x773B7B5E+286]
        RtlGetAppContainerNamedObjectPath [0x773B7B2E+238]

Exception ignored in: <function Chrome.__del__ at 0x0000022D54C12160>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit
OSError: [WinError 6] Das Handle ist ungültig
Exception ignored in: <function Patcher.__del__ at 0x0000022D54C11440>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 273, in __del__
OSError: [WinError 6] Das Handle ist ungültig

Did anyone had the same error, but more importantly has a solution?

**Comment by Fakir2023** [comment]
I also have this kind of error
